### ISSUE TITLE
Csv parser error when EP issues summary reports

### ISSUE THREAD

**Issue by Sarah-Ju** [locie/energy_plus_wrapper#2]
Hej!

When for some reason we need energy plus to issue a summary report after a simulation, run(idf) runs into an error when it comes to the point of getting the data from the tmp directory.

I believe this comes from the fact that EP summary reports are issued in csv format, and the run function (in line 211 of main.py) tries to parse data from any csv file in the tmp directory, resulting in an error when it reads the summary csv.

Of course not issuing the report in the first place fixes the bug, but maybe run(idf) could just try to read the file named 'eplus.csv' ?
As an option, we could consider that run(idf) would also deal with copying the csv reports in the final directory too.

Sarah

**Comment by celliern** [comment]
Hello! 

I tried a path (see tag [patch_issue_2](https://github.com/locie/energy_plus_wrapper/releases/tag/path_issue_2)).

I will need some help to test it, as I'm not a eplus user myself and I do not have a .idf that test that user case. Could you run some test on that version?

**Comment by Sarah-Ju** [comment]
Thanks !
I tried with my usual 'EnvelopeSummary' which delivers one report and with 'AllSummaryMonthlyAndSizingPeriod' which delivers all possible reports (into one csv file though, outcome in the temp directory is the same), a run on both worked, dataframe saved is indeed the simulation data. Seems good to me !
